### ISSUE TITLE
Typo in javadoc in Modulith.additionalPackages method, misplaced copy right header in DocumenterTest

### ISSUE THREAD

**Issue by dkapil** [olivergierke/moduliths#22]
Type in java doc of additionalPackages method in Modulith.java. "shall be considered" repeated twice.

> Defines which additional packages **shall be considered shall be considered** as modulith base packages in addition to the one of the class carrying this annotation

Copyright header is placed above the class name in DocumenterTest.java it should be above package declaration.

**Comment by olivergierke** [comment]
Thanks for reporting that. Should be fixed now!
